AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Persist an item to a DynamoDB table from Lambda
Resources:
  ##########################################################################
  #   Lambda Function                                                      #
  ##########################################################################
  LambdaPutDynamoDB:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          DatabaseTable: !Ref DynamoTable
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - DynamoDBWritePolicy:
            TableName: !Ref DynamoTable

  ##########################################################################
  #   DynamoDB                                                            #
  ##########################################################################
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
##########################################################################
#   OUTPUTS                                                              #
##########################################################################

Outputs:
  LambdFunction:
    Value: !Ref LambdaPutDynamoDB
    Description: LambdaPutDynamoDB function  Arn

  DynamoDbTable:
    Value: !Ref DynamoTable
    Description: DynamoDb Table
